### ISSUE TITLE
File symlinking

### ISSUE THREAD

**Issue by phroggyy** [rawkode/comtrya#20]
### Is this a feature request or a bug report?

Feature request

### Describe the feature

It should be possible to symlink files with Comtrya. Preferably, this would be its own action, distinct from copying. Proposed syntax is similar to copy:

```yaml
actions:
  - action: file.symlink
    from: gitconfig
    to: /Users/rawkode/gitconfig
```

Alternatively, we could make it `file.link` with `symbolic` being an option (default `true`).
