### ISSUE TITLE
add update flag to package.install

### ISSUE THREAD

**Issue by bketelsen** [rawkode/comtrya#26]
given this action:

```
actions:
  - action: package.install
    name: git
```
running the module will install git as expected the first time.  with a `brew` provider it will fail if git has a version bump on a subsequent apply.

```
 ERROR manifest_run{manifest="git"}:package.install{provider="Homebrew"}: Error: git 2.30.2 is already installed
To upgrade to 2.31.0, run:
  brew upgrade git

 ERROR manifest_run{manifest="git"}: Failed to install git
 ERROR manifest_run{manifest="git"}: Failed
```
`comtrya` should handle this gracefully in the default case, because `git` is installed. 

it would be useful to have a flag or an alternative action to either install or update the package.
if the package is installed and latest, no actions are taken. If the package is installed and outdated, the package is updated. if the package isn't installed, the package is installed.

options:
```
actions:
  - action: package.latest
    name: git
```
or
```
actions:
  - action: package.install
    update: true
    name: git
```

**Comment by rawkode** [comment]
@bketelsen Hmm. That's odd! The Homebrew provider checks in your paths for the Homebrew installation. When I `-vv` this, I see:

` TRACE manifest_run{manifest="git"}:package.install{provider="Homebrew"}: git: found in Cellar`

I'm curious why this isn't the case for you.

Can you run your Git module in isoloation with `-m` and show me the `-vv` output, please?

**Comment by bketelsen** [comment]
output [here](https://gist.github.com/bketelsen/a0d00283b7339856c5e66061ac33221b)

**Comment by rawkode** [comment]
OK. I'll keep this issue open for the update / latest request.

The Git problem was fixed by using the host machines `brew --prefix`. Closed by #28

**Comment by martintc** [comment]
Wouldn't be better to provide a generic action to run updates? This seems like a bit too dependent on the specific behavior of homebrew. Apt, DNF, and many of the other package managers don't have this kind of behavior.

**Comment by rawkode** [comment]
Now that we have subcommands, I'm curious if `comtrya packages update` would be useful?

It could scan manifests, discover packages, and attempt updates?

**Comment by JustinBacher** [comment]
I'm in agreeance with @martintc here. I think aprovider actions would be best. Something along these lines:

```yaml
actions:
  - action provider.update
    # Update all available package managers
    name: all

  - action provider.update
    # Update specific ones
    name: brew
    # or
    list:
    - brew
    - winget
    - yay


  - action package.upgrade
    # Upgrade all packages (so not to have name conflicts with a package that may have the name all)
    all: true
    # Only specific ones
    name: git
    # Or a list of them
    list:
    - git
    - curl
    # Specify a provider or all
    provider: all
    # Or a list of providers
    provider:
    - brew
    - paru
```
